### ISSUE TITLE
Generate short links for upload and/or files

### ISSUE THREAD

**Issue by peperunas** [root-gg/plik#185]
Hello!
I've noticed that every upload is automatically shortened once a service is specified in `plikd.cfg`.
I think it would be better to "shorten on demand", i.e: when a user wants to do it. 
Furthermore, it would be nice to be able to shorten specific files too, not only the "main" upload.

Thank you guys, you are doing a GREAT job!

**Comment by camathieu** [comment]
Hello,

We want to refactor shortening since a long time, what's left of it is mostly 1.0 stuff.

As you noticed there are many downsides to shorten every links :
 - it leaks upload URLs to a third party ( less of a consern if you own it )
 - it reduce the security given by the upload id length
 - if the third party does not respond at the upload creation time you won't have a shortlink
 - we are not really into maintaining a long list of modules for every URL shortener

Also I'm not sure that this should be frontend/cli or backend stuff as different users might want to use different shortener.

We did not remove the feature for now but we are close to it since a long time. It's not that hard to copy the link to your favorite shortener. 

We even wondered if we could not implement a url shortener inside Plik ^^

We'd be happy to hear what do you think about all that.

**Comment by peperunas** [comment]
At first I thought it would have been awesome to let Plik's users to set up custom APIs from various domains but I think it would be prone to security issues. (e.g set up a hook on every upload)

I think that a "homemade" shortener built in Plik would be the best bet, as for now.

What do you think about it?

**Comment by camathieu** [comment]
1.2.1 is a big cleaning release, so we'll remove the current version of the shorten feature. 
https://github.com/camathieu/plik/commit/d4b994425509077dc96bd9a617af37a58a34954f

In the mean time we are gathering features for 1.3. Let's try to define the need more clearly :

Implementing that right in Plik would at least make sure that we don't have to fear third party latency / availability. It can be only a few methods to add to the metadata backend ( a new collection ). I think that the feature should also be implemented also in the cli.

A few questions in bulk : 
Do we want to implement shortening on the same domain or a separate one ?
Do we want the shortest possible links ( plik.root.gg/1 ) or something with like 4 or 6 alphanumerical characters ?
Does the short links need to be persisted with the upload so only one short link per upload exists or not ?
Does the short link need to be linked with the user that created it ?
Wouldn't it make more sense to do it in a side project so you can also use it to shorten other links ?
Does something like this already exists and would be easy to integrate ?

We might have a bit of an issue with the lack of /api in the routes.

**Comment by peperunas** [comment]
> Do we want to implement shortening on the same domain or a separate one ?

Same domain

> Do we want the shortest possible links ( plik.root.gg/1 ) or something with like 4 or 6 alphanumerical characters?

I think that 4 to 6 characters is the best bet here. I'd like to add a feature though: **custom links**.
i.e: it would be great to have the "standard" shortening feature to do something like `root.plik.gg/abcedf` but the user could decide to transform it to `root.plik.gg/photoalbum`.

> Does the short links need to be persisted with the upload so only one short link per upload exists or not ?

Yes

> Does the short link need to be linked with the user that created it?

I don't think this is needed

> Wouldn't it make more sense to do it in a side project so you can also use it to shorten other links ?

I already created a side-project like this in order to practice some Python web development but I think it would be MUCH more convenient and less time-consuming to have it already built-in.

> Does something like this already exists and would be easy to integrate ?

There are plenty of open source projects here on Git: [click me!](https://github.com/search?l=Go&langOverride=&q=url+shortener&repo=&start_value=1&type=Repositories)

:-)

**Comment by damajor** [comment]
> Do we want to implement shortening on the same domain or a separate one ?

I would suggest to make a separate server (another daemon with its own settings) in order to address same and separate domains. Like an external url shortener but made by you and for the only purpose of Plik.

> Do we want the shortest possible links ( plik.root.gg/1 ) or something with like 4 or 6 alphanumerical characters ?

+1 for something with 4 to 6 chars. The idea of @peperunas with the custom url is also nice.

> Does the short links need to be persisted with the upload so only one short link per upload exists or not ?

Same TTL.

> Does the short link need to be linked with the user that created it ?

If the user is logged yes, if not then only link it to the file.

> Wouldn't it make more sense to do it in a side project so you can also use it to shorten other links ?

My first remark :)

> Does something like this already exists and would be easy to integrate ?

Maybe this can help [https://www.google.fr/search?q=golang+url+shortener](https://www.google.fr/search?q=golang+url+shortener)

**Comment by ediazrod** [comment]
is issue is closed because is solved, or we will not have sort links never again?

Regards!
