### ISSUE TITLE
Cannot upload

### ISSUE THREAD

**Issue by k0nsl** [root-gg/plik#196]
I deployed `plikd` via `apt-get` on my Debian machine and I can access the instance fine. However, when I try to upload a file, it spits out this:
```
Unable to parse source IP address
```
I am running `plikd` behind `caddy` (as reverse proxy). Any ideas on how to get this working?

**Comment by camathieu** [comment]
Hello, 

The configuration directive for caddy seems to be (untested) :

```
header_upstream X-Forwarded-For {remote}
```

We have also patched the code https://github.com/root-gg/plik/commit/a43ddc4e994d3b02d0859f9dd869b8895e25dd03 so that should not be a problem for later releases. We will update the debian repository as soon as possible.


See also : https://github.com/root-gg/plik/issues/176
