### ISSUE TITLE
[Help or Bug?] Stream feature seems broken

### ISSUE THREAD

**Issue by damajor** [root-gg/plik#216]
Hi,

I am trying to do some experiments using the streaming feature but it does not seem to work.

Here is the behavior I get:
 * Both Computers: Open Plik
 * Computer 1: Enable stream
 * Computer 1: Drop a file

=> At this moment nothing is different from a classic upload, no custom URL is generated so I cannot provide the link to the other computer.
So I tried the following:
 * Computer 1: Click on upload, then Plik provides me a custom URL and my browser starts to upload the file
 * Computer 2: Load the custom URL

=> Now the download is starting while the file is uploaded **at the same time**.

My guess is that the Plik server is in the middle of the transfer.

Could you help me to understand how to use the streaming feature and also how it works technically ?

Thx.

**Comment by bodji** [comment]
You're right.

The streaming mode is not a peer-to-peer feature.  It needs the plik server.

The feature works this way : 

1. Computer 1 enables stream mode (in webApp or CLI client)
2. When user hit upload button (or start the CLI client with file), an upload is created on plik server, and we return the upload and file id (so we can have the file URL to give).
3. Computer 1 makes the upload request to the server.
4. Since stream mode is enabled, the plik server only store http request and leaves it opened (with a timeout)
5. Computer 2 access to the link
6. The plik server retrieves the computer 1 http request and binds it to computer 2 http request, and the content of the first is sent to the second one.

**Comment by camathieu** [comment]
The "starts to upload the file" might also need a bit of explanation.
There is a buffer somewhere in the way in the Plik server side, or maybe in nginx or even the web browser I'm not sure, to smooth out the upload speed more likely.
It seems to be around 8MB though.
When the file is loaded into that buffer the progress bar fills, if the file is smaller that 8MB if fills entirely and if it is smaller it fills up to a certain percentage then it blocks.

Then when the second connection recaches the server, data starts flowing from the first http.Request body to the second http.Response body without being stored on the server.
