### ISSUE TITLE
Local User

### ISSUE THREAD

**Issue by hawkuz** [root-gg/plik#291]
Could someone explain, howto configure the Authentication to use local user Autenthication?

**Comment by wpa1160** [comment]
Same here: Created user with "./plikd --config ./plikd.cfg user create --login" and entered the details under "Authentication". User name/password combination must be working since there's no "Oops ! (400)" error but obviously that information isn't passed to the system. The login page just flashes and requests user name and password again.

Tried using Firefox, Chrome and Edge.

**Comment by camathieu** [comment]
Hello,

For now authentication only work in HTTPS due to secure cookies. It will be
disabled by default and part of the EnhancedWebSecurity configuration
option in 1.3-RC2

**Comment by camathieu** [comment]
https://github.com/camathieu/plik/commit/c7b6cfdae39d541400555b834f280073de77454e

**Comment by camathieu** [comment]
https://github.com/root-gg/plik/pull/293 has been merged

**Comment by hawkuz** [comment]
Works with SSL enabled.

**Comment by camathieu** [comment]
Awesome :)

**Comment by hawkuz** [comment]
Great Support, thanx!
