### ISSUE TITLE
Unable to delete files

### ISSUE THREAD

**Issue by pieterhouwen** [root-gg/plik#352]
I noticed that on our instance of Plik files weren't being removed after they expired so I took a look at the logs and found the following:

[01/13/2021 15:47:32][WARNING ] unable to delete file zLWxo9KAgtTktxiJ/pbPFN5vCHKI8eI4p : no such file or directory
[01/13/2021 15:47:32][WARNING ] no such file or directory
Can't remove upload zLWxo9KAgtTktxiJ because 1 files are still not deleted
Can't remove upload AfLAYpe7bIukTxhb because 1 files are still not deleted
Can't remove upload 1gD7wZTNxrk8CYwt because 1 files are still not deleted

This continues for a while. There's now a backlog of undeleted files for about a month even though the max ttl is set to a week.

What can cause this behavior and why does it also affect the future uploaded files?

**Comment by camathieu** [comment]
There might be an issue with the delete logic. It should not break if the files have already been deleted.

**Comment by speed47** [comment]
This happens due to the `ForEachRemovedFile` func logic:
https://github.com/root-gg/plik/blob/b0f32d39daf56195415004429815ddc147c5ab45/server/metadata/file.go#L118-L121
`f` in the context of the caller (`PurgeDeletedFiles`) is a func that is responsible for actually deleting files from the storage backend, and it does return an error if it fails (for example, because the file no longer exists). This makes the `ForEachRemovedFile` return early and not even try to delete the remaining files.
